spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI}
firebase.project-id=${FIREBASE_PROJECT_ID}
stripe.secret.key=${STRIPE_SECRET_KEY}
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE:MongoDB}
spring.data.mongodb.auto-index-creation=true

logging.level.org.mongodb.driver=INFO
